version: '2'
services:
  wp-base:  
    build: .
    image: mattiashem/wp-base:5.3
    ports:
      - 8833:8000
    environment:
      DBHOST: db
      SITENAME: wordpress
      DBPASS: wordpress
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
