agent:
  label: builder-go
  container: go
env:
  - name: GIT_COMMITTER_EMAIL
    value: jenkins-x@googlegroups.com
  - name: GIT_COMMITTER_NAME
    value: jenkins-x-bot
  - name: GIT_AUTHOR_EMAIL
    value: jenkins-x@googlegroups.com
  - name: GIT_AUTHOR_NAME
    value: jenkins-x-bot
  - name: ORG
    value: northamlin-com

pipelines:
  release:
    build:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/northamlin-com/$APP_NAME:\$(cat VERSION)
