apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.url }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    #certmanager.k8s.io/cluster-issue: "letsencrypt-prod"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    nginx.org/client-max-body-size: 250M
    nginx.org/proxy-body-size: 250M

spec:
  tls:
  - hosts:
    -  {{ .Values.url }}
    secretName: {{ .Values.url }}
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - path: /
        backend:
         serviceName: {{ .Values.name }}-service
         servicePort: {{ .Values.port }}
