# ssd-storageclass.yaml
{{- if not (lookup "storage.k8s.io/v1" "StorageClass" "" "ssd") }}
{{- if ( eq "ssd" .Values.storage_class ) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- end}}
{{- end}}
